### ISSUE TITLE
fix revision in display name

### ISSUE THREAD

**Issue by sholl** [52North/restful-timeseries-proxy#3]
When using the tomcat manager the display-name of a build does not show up with the correct revision-number. Would be helpful to know which revision the build was based on though.

![zg2015-timeseries-display-name](https://cloud.githubusercontent.com/assets/1610827/4556282/6a10f89a-4ec7-11e4-8a6e-85a21b53b42f.PNG)

**Comment by ridoo** [comment]
fixed with https://github.com/52North/restful-timeseries-proxy/commit/99602c9a3421f5a66d365d29a0bfe50e67e0a4f1
